### ISSUE TITLE
Roadmap for introducing code concepts

### ISSUE THREAD

**Issue by matthew-brett** [resampling-stats/resampling-with#37]
We should make roadmap that sets out the list of chapters, and the various code concepts and constructs that the students will need, and where we introduce them, as in:

- [x] about_technology : notebook, variables
- [ ] resampling_with_code : functions, arrays, array-indexing, for loops - 'resampling_with_code'
- [ ] Strings?
- [ ] Random.choice with probabilities?
- [ ] User functions

**Comment by matthew-brett** [comment]
I'm currently filling this out in https://github.com/resampling-stats/resampling-with/blob/main/notes/general.md#code-topics - but happy to move that elsewhere.
